### ISSUE TITLE
Add Task Modal Form

### ISSUE THREAD

**Issue by anshisinghh** [cse110-sp24-group1/cse110-sp24-group1#10]
### Add Task Modal Form

---

**Tasks:**

- [x] Design a modal form layout that includes input fields for the task's title, description, label, and due date
- [x] Implement JavaScript functionality to display the modal form when the user wants to create a new task
- [x] Add a button to the trigger the display of the modal form for creating tasks

**Additional Context:**
Using a modal form for creating tasks can improve the user experience by providing a focused and contextually relevant interface for adding new tasks.

---

**Labels:**
frontend, enhancement, core feature

---
