### ISSUE TITLE
Make buttons tabable

### ISSUE THREAD

**Issue by PussakornCH** [cse110-sp24-group1/cse110-sp24-group1#108]
### Make buttons tabable

---

**Tasks:**

- [ ] all buttons or input fields just be navigable through tabbing on your keyboard
- [ ] Ensure no tab traps
- [ ] Trap tab on modals 

**Additional Context:**
Look up accessibility requirements accessible
(HTML accessibility feature)

---

**Labels:**
frontend, enhancement

---
