### ISSUE TITLE
Github Repo Organization

### ISSUE THREAD

**Issue by anshisinghh** [cse110-sp24-group1/cse110-sp24-group1#35]
### Github Repo Organization

---

**Tasks:**

- [ ] Ensure that all code follows the established code style guidelines to ensure consistency in code style, formatting, and naming conventions across the project
- [ ] Organize front-end and back-end code into folders for each property
  - [ ] Create folders such as `assets`, `src`, `schemas`, etc., to organize front-end and back-end code files based on their respective properties and functionalities

**Additional Context:**
Following consistent code style and organizing code into folders will improve code readability, maintainability, and collaboration among team members.

---

**Labels:**
backend, frontend, documentation

---
