### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by anshisinghh** [cse110-sp24-group1/cse110-sp24-group1#4]
### Navigation Bar

---

**Tasks:**

- [x] Design and implement three tab links for the home page, task list, and settings (or toggle switch for dark/light mode)
- [x] Design and implement clearly labeled links or buttons for different sections on the left hand side of the screen, ensuring consistency and easy navigation
- [x] Test the navigation elements to ensure they are displayed correctly and function as expected on different screen sizes

**Additional Context:**
Implementing these navigation elements will improve the user experience of the application by providing clear and consistent navigation options for users.

---

**Labels:**
frontend, enhancement, core feature

---
