### ISSUE TITLE
Initial data schema tests 

### ISSUE THREAD

**Issue by Jabo10** [cse110-sp24-group1/cse110-sp24-group1#55]
### Testing data schema

---

**Tasks:**

- [] Create test cases to cover all functionality of storage of data 
- [] Execute test cases to verify that the task list functions correctly
- [x] Identify and report any bugs or issues found during testing
- [x] Ensure that the tests themselves are easy to understand

**Additional Context:**
Testing the functionality of how the data works for the folders, notes, and task list will ensure everything is saved and returned correctly.  I would say that more tests will have to be added come review specifically for deleting functionality and retrieving a specific folder.

---

**Labels:**
testing

---
